heat_template_version: 2015-04-30

description: >
  Software Config to drive os-net-config with nics and with VLANs attached for the controller role.

parameters:
  ControlPlaneIp:
    default: ''
    description: IP address/subnet on the ctlplane network
    type: string
  ExternalIpSubnet:
    default: ''
    description: IP address/subnet on the external network
    type: string
  InternalApiIpSubnet:
    default: ''
    description: IP address/subnet on the internal API network
    type: string
  TenantIpSubnet:
    default: ''
    description: IP address/subnet on the Tenant network
    type: string
  StorageIpSubnet:
    default: ''
    description: IP address/subnet on the storage network
    type: string
  StorageMgmtIpSubnet:
    default: ''
    description: IP address/subnet on the storage mgmt network
    type: string
  ManagementIpSubnet: # Only populated when including environments/network-management.yaml
    default: ''
    description: IP address/subnet on the management network
    type: string
  TenantNetworkVlanID:
    default: 70
    description: Vlan ID for the tenant network traffic.
    type: number
  ExternalNetworkVlanID:
    default: 901
    description: Vlan ID for the external network traffic.
    type: number
  InternalApiNetworkVlanID:
    default: 30
    description: Vlan ID for the internal_api network traffic.
    type: number
  StorageNetworkVlanID:
    default: 40
    description: Vlan ID for the storage network traffic.
    type: number
  InbandManagementVlanId:
    default: 117
    description: VLAN ID for the Internal Management network
    type: number
  StorageManagementNetworkVlanID:
    default: 50
    description: Vlan ID for the storage mgmt network traffic.
    type: number
  ExternalInterfaceDefaultRoute:
    default: '192.168.91.253'
    description: default route for texternal network
    type: string
  ControlPlaneDefaultRoute:
    default: '10.1.20.2'
    description: default route
    type: string
  ControlPlaneSubnetCidr: # Override this via parameter_defaults
    default: '24'
    description: The subnet CIDR of the control plane network.
    type: string
  DnsServers: # Override this via parameter_defaults
    default: []
    description: A list of DNS servers (2 max for some implementations) that will be added to resolv.conf.
    type: comma_delimited_list
  EC2MetadataIp: # Override this via parameter_defaults
    description: The IP address of the EC2 metadata server.
    type: string

resources:
  OsNetConfigImpl:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
        os_net_config:
          network_config:
            -
              type: interface
              name: eth0
              use_dhcp: false
              addresses:
                -
                  ip_netmask:
                    list_join:
                      - '/'
                      - - {get_param: ControlPlaneIp}
                        - {get_param: ControlPlaneSubnetCidr}
              routes:
                -
                  ip_netmask: 169.254.169.254/32
                  next_hop: {get_param: EC2MetadataIp}
                -
                  defroute: yes
                  next_hop: {get_param: ControlPlaneDefaultRoute}
            -
               type: interface
               name: eth1

            -
               type: interface
               name: eth2
            -
               type: vlan
               device: eth2
               vlan_id: {get_param: InternalApiNetworkVlanID}
               addresses: 
                 -
                   ip_netmask: {get_param: InternalApiIpSubnet}
               defroute: no
            
            -
                type: ovs_bridge
                name: br-tenant
                use_dhcp: false
                members:
                  - 
                    type: interface
                    name: eth3
            -
               type: interface
               name: eth4
            -
               type: vlan
               device: eth4
               vlan_id: {get_param:  ExternalNetworkVlanID}
               addresses: 
                 -
                   ip_netmask: {get_param: ExternalIpSubnet}
               routes:
                 -
                   ip_netmask: 0.0.0.0/0
                   next_hop: {get_param: ExternalInterfaceDefaultRoute}
               
            -
               type: interface
               name: eth6
            -
               type: vlan
               device: eth6
               mtu: 9000
               vlan_id: {get_param: StorageNetworkVlanID}
               addresses: 
                 -
                   ip_netmask: {get_param: StorageIpSubnet}
               defroute: no
            -
               type: interface
               name: eth7
            -
               type: vlan
               device: eth7
               mtu: 9000
               vlan_id: {get_param: StorageManagementNetworkVlanID}
               addresses: 
                 -
                   ip_netmask: {get_param: StorageMgmtIpSubnet}
               defroute: no
  
            -
                type: ovs_bridge
                name: {get_input: bridge_name}
                use_dhcp: false
                members:
                  - 
                    type: interface
                    name: eth8
                    primary: true               

outputs:
  OS::stack_id:
    description: The OsNetConfigImpl resource.
    value: {get_resource: OsNetConfigImpl}
